deploy:
    before:
        - webapp

webapp:
    path:   .
    public:
        assets:
            chmod: '0777'
        index.php:
            once:     true
            template: webapp/web/index.twig
        robots.txt:
            once:     true
            template: webapp/web/robots.twig
        favicon.ico:
            once:     true
            copy:     $params['favicon.ico']
    runtime:
        chmod:  '0777'
